INPUT:
  SLICE_NUM: 9
  MIN_SIZE_TRAIN: (400, 600, 800, 1000, 1200)
  MAX_SIZE_TRAIN: 1200
  IGNORE_EMPTY: True
MODEL:
  PIXEL_MEAN: [0, 0, 0, 0, 0, 0, 0, 0, 0]
  PIXEL_STD: [1., 1., 1., 1., 1., 1., 1., 1., 1.]
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_vovnet_fpn_backbone"
    FREEZE_AT: 0
  VOVNET:
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 100  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 100
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NMS_THRESH_TEST: 0.1
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
DATASETS:
  TRAIN: ("coco_tjmu_14f2", "coco_tjmu1_14f2", "coco_tjmu2_14f2", "coco_lgmn_14f2",)
  TEST: ("coco_test_all",)
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
TEST:
  DETECTIONS_PER_IMAGE: 100
VERSION: 2
